# my first programe hhhhhhhhhh
user_name = input("EAMIL ADRESS  :")
print("...............................................................................")
password_key = input("password  :")
print("...............................................................................")
type_of_email = input("GMAIL or YAHOO or MICROSOFT :::")
print("...............................................................................")
print("...............................................................................")
print("wait a second"),print("wait a minute"),print("wait a hour"),print("wait a month")
print("...............................................................................")
print("wait a second"),print("wait a minute"),print("wait a hour"),print("wait a month")
print("...............................................................................")
print("wait a second"),print("wait a minute"),print("wait a hour"),print("wait a month")
print("...............................................................................")
print("wait a second"),print("wait a minute"),print("wait a hour"),print("wait a month")
print("...............................................................................")
print ("hahahahahahahahahahahahahahahahahahahahahahahahaahahahahahahahahahahahahahahah")
print("...............................................................................")
print(" if you put your private info")
print("...............................................................................")
print("you are crazy man")
print("...............................................................................")
print("and ilove you to be more crazy than the past")
print("...............................................................................")
print("bellow your information")
print("...............................................................................")
print(" i will selling to google or facebook")
print("...............................................................................")
print("of corse for giving me money money money")
print("...............................................................................")
print("the eamil is not correct :",user_name)
print("...............................................................................")
print("the password dose not exist :",password_key)
print("...............................................................................")
print("you know this is not an important thig :",type_of_email)

rating_my_hacking_skills= input("your rating  :")
print(rating_my_hacking_skills,"is a small or big nunber .however,I respect your rating but this is not enough") 
